workflows:
  ios-release:
    name: iOS Release (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m
    environment:
      groups:
        - appstore_credentials   # grupa sekretów w Codemagic
      vars:
        BUNDLE_ID: "pl.wowo.moj-owoc"
        APP_NAME: "Mój owoc"
      flutter: stable
      xcode: latest
    triggering:
      events: [push]
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod install || pod repo update && pod install
          cd ..
      - name: Build ipa (release)
        script: |
          flutter build ipa --release --build-name=1.0.0 --build-number=$CM_BUILD_ID
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/app.dSYM.zip
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups: ["Internal Testers"]
